### ISSUE TITLE
Add Miitomo Questions

### ISSUE THREAD

**Issue by larsenv** [fl0co/RC24-Bot#107]
Please add the whole list of questions from here from the Question_List section: https://gist.github.com/jaames/1b14264e322855fb5a67d4d934e95e5f

You don't have to embed it, ad the command can be named !topicchange if you want.

Thanks.

**Comment by Artuto** [comment]
It was already decided that Miitomo questions would not be added because there is no easy way to parse that markdown file unlike EVC's YAML

**Comment by larsenv** [comment]
We don't need it in markdown. If I put it in a text file with one question per line can you add that?

**Comment by Artuto** [comment]
Put it like this in a YML file and I'll look into it (only english is needed)
![image](https://user-images.githubusercontent.com/9273973/90971129-5f381f00-e4d2-11ea-89c6-64fd18ffa3c3.png)

**Comment by larsenv** [comment]
I made a YML for the questions, now can they be imported? Of course, all the command would need to do is just pick one of these randomly.

https://cdn.discordapp.com/attachments/287740297923002368/748654266352140288/miitomo_questions.yml
