### ISSUE TITLE
command break: !revive (or @Riiconnect24 Bot revive)

### ISSUE THREAD

**Issue by Exorcism0666** [fl0co/RC24-Bot#122]
![image](https://user-images.githubusercontent.com/46537034/132939131-02ec1504-4747-4482-96dc-e527fea18c6b.png)

![image](https://user-images.githubusercontent.com/46537034/132939222-92cf1ac3-d5a5-4f04-9bf4-c8313ab86691.png)

**As on the picture above, the command does not work**

**Comment by Artuto** [comment]
That is intended, the command has been removed due to performance reasons.

**Comment by Exorcism0666** [comment]
Okay, thanks for the information!
