### ISSUE TITLE
Birthday parsing is broken

### ISSUE THREAD

**Issue by larsenv** [fl0co/RC24-Bot#30]
This might be server-side but parsing someone's birthday is broken. Seriel was trying to fix it earlier today but she might have broke it more.

![screen shot 2017-07-11 at 1 34 35 pm](https://user-images.githubusercontent.com/4673969/28084288-c9b37314-663d-11e7-9608-f0ea7e3b7b5f.png)

**Comment by spotlightishere** [comment]
This is an issue with the fact I'm parsing it using Ruby's native parser.
Should probably change this.

**Comment by spotlightishere** [comment]
Fixed in 19a89e2, due to a completely different issue.
