### ISSUE TITLE
Birthday duplicate checking

### ISSUE THREAD

**Issue by larsenv** [fl0co/RC24-Bot#32]
The bot should check if a user's birthday is in the birthdays.yml file before adding it again. If it's on a different day (IDK why you'd change it), delete the old entry.

**Comment by joscomputing** [comment]
It should be checking this on runtime for birthdays + adding, if only
adding feel free to copy the logic over.

**Comment by spotlightishere** [comment]
This should be already done -- if not, this can be reopened.
