### ISSUE TITLE
Mailparse doesn't throw an error if the nwc24msg.cfg is invalid, is longer than it should be, etc.

### ISSUE THREAD

**Issue by KuraiKokoro** [fl0co/RC24-Bot#39]
> Parse error: undefined
> Call stack: undefined KaitaiUnexpectedDataError: expected [80,75], but got [87,99]

**Comment by spotlightishere** [comment]
Interesting, https://github.com/fl0co/RC24-Bot/blob/master/modules/mailparse.rb#L41-L45 should be taking care of that. will investigate upon having time

**Comment by KuraiKokoro** [comment]
Turns out my ksy file was corrupted...

**Comment by KcrPL** [comment]
¯\_(ツ)_/¯
