### ISSUE TITLE
Commands are case sensitive.

### ISSUE THREAD

**Issue by KuraiKokoro** [fl0co/RC24-Bot#40]
This should be relatively to fix, but I don't have enough knowledge about Ruby to make a proper PR.

**Comment by spotlightishere** [comment]
Define what part is case sensitive.. the arguments? the defined command itself?

**Comment by KuraiKokoro** [comment]
https://i.imgur.com/G3sYb46.png

**Comment by spotlightishere** [comment]
Are you sure that's the right screenshot? xP

If you mean `!code` vs `!Code`, as far as I know discordrb intends this to be this way. I don't know of an option to disable sensitivity. I could possibly create a separate function containing code and multiple commands running it however

**Comment by KuraiKokoro** [comment]
Hm, I assumed it'd be a simple make a string lowercase, but if discordrb is making that impossible then it'd be more of a mess to add, and probably not worth bothering with at all.

Also, yes, that IS the wrong screenshot. Xfce4-screenshot is acting like a buggy mess

**Comment by KuraiKokoro** [comment]
If you can find a way to do this without adding a bunch of lines, then I'll reopen this but yeaah, perhaps I was quick to assume that it'd be easy to do.

**Comment by spotlightishere** [comment]
Lol, you're fine. Commands are defined as 
```
command(:name) do |event|
etc
end```

I could create capitalized versions of the names theoretically. Needs investigation.

**Comment by therealprocyon** [comment]
@spotlightishere regarding this: with @Seriell's commandrb you can do this more easily

**Comment by spotlightishere** [comment]
@therealprocyon While that may be true, I feel that converting to commandrb would end up being a pain due to rubocop and the size of certain commands. Event syntax wouldn't mix with commandrb.

Also Seriel said not to use it until it was much much more stable 😛

**Comment by therealprocyon** [comment]
Alright then, that's true. AFAIK commandrb is now a public gem.

**Comment by ArtutoGamer** [comment]
~~And what if we port this to JDA heh~~

**Comment by spotlightishere** [comment]
I'm legitimately considering it.

**Comment by ArtutoGamer** [comment]
~~lets see what happens~~
http://m.imgur.com/gallery/7SpqkNB

**Comment by spotlightishere** [comment]
I think what's needed is a reimplementation of event listeners tbh. You're
welcome to port but I'll never want to change it entirely to JDA.

(Sounds like a fun experiment)

**Comment by Seriell** [comment]
Oh god it actually did get converted as well
*this was the beginning of the end*

**Comment by spotlightishere** [comment]
Oi :(

**Comment by Seriell** [comment]
"I'll never want to change it entirely to JDA."
Suuuuuuurrrrrrrrrreeeeeeeeeeee
