### ISSUE TITLE
Add !code rename and allow the code types to work in capitals

### ISSUE THREAD

**Issue by JonM313** [fl0co/RC24-Bot#60]
If the things in the title are added they will be useful and will make things easier!

**Comment by Artuto** [comment]
Code types now work in capitals.

I'm going to wait until I rewrite the db system to MySQL and i'll add the rename command.

**Comment by yeah-its-gloria** [comment]
Didn't knew you wait so long

**Comment by Artuto** [comment]
The MySQL rewrite was scrapped.
