### ISSUE TITLE
Move to MySQL

### ISSUE THREAD

**Issue by Artuto** [fl0co/RC24-Bot#63]
Due recent issues with redis ~~and it being too dumb~~.

I have discussed with @larsenv and we think the best option is to move to MySQL.

This will need a rewrite of the database system.

**Comment by AggPro** [comment]
Smells like MariaDB

**Comment by Artuto** [comment]
I'd rather use JSON. No thanks.

**Comment by Artuto** [comment]
Closing this as the Redis Database worked.

**Comment by Artuto** [comment]
What a fucking meme

**Comment by yeah-its-gloria** [comment]
> blaming Redis due to faulty configuration

**Comment by Artuto** [comment]
>redis has been working for the latest 4 months without issue.

**Comment by Apfel** [comment]
I'll work on it, hopefully you will be happy with MySQL and won't `lose` your codes anymore.

**Comment by Artuto** [comment]
NONO NO NO NO CLOSE THE REPO.

**Comment by Apfel** [comment]
Very nice English, I totally understood you.

**Comment by Artuto** [comment]
Being worked in mysql-rewrite branch.
