### ISSUE TITLE
Fix NEWS/FORE error code case

### ISSUE THREAD

**Issue by larsenv** [fl0co/RC24-Bot#75]
!error NEWS000006 works.

!error news000006 doesn't.

Also, it should say that the riiconnect24-batteryfix trick only works with the Forecast Channel.

**Comment by Artuto** [comment]
>Also, it should say that the riiconnect24-batteryfix trick only works with the Forecast Channel.

It already does: `put(6, "Invalid data. If getting this on the Forecast Channel, try again in a few minutes. If you're still getting this error, follow https://wii.guide/riiconnect24-batteryfix and it might fix it.");`
