### ISSUE TITLE
Add country flag to profile

### ISSUE THREAD

**Issue by larsenv** [fl0co/RC24-Bot#77]
That'd be a pretty cool feature, the flag would be represented by an emoji, of course. I just thought of it.

**Comment by Artuto** [comment]
In what part of the command this should be shown?

**Comment by larsenv** [comment]
At the top where it says the username you're looking up, please.

**Comment by larsenv** [comment]
@Artuto Could you please make this higher priority? It'd be cool to have this as a feature. Or maybe other emoji can be used.

**Comment by Artuto** [comment]
I'm not sure how to have a list of countries.. probably will just add main ones (US, Canada, Mexico, Brazil, Argentina, Colombia, Venezuela, UK, France, Spain, Germany, etc...)

**Comment by larsenv** [comment]
I just wanted it to be represented by a Discord flag emoji. Not the name of the country. That's doable, right?

**Comment by Artuto** [comment]
Because users would need to enter the country name.

**Comment by larsenv** [comment]
Can't they run a command to set it by using the emoji as an argument, and maybe error out if the emoji doesn't match the name used for flags?

**Comment by Artuto** [comment]
I dont get the name (`:flag_whatever:`) and instead only a unicode character so can't check it.
