### ISSUE TITLE
Cant add it to my server

### ISSUE THREAD

**Issue by sastofficial** [fl0co/RC24-Bot#80]
i cant add it

**Comment by Artuto** [comment]
At least bother to read the `!help` command.

**Comment by sastofficial** [comment]
> At least bother to read the `!help` command.

i did
and stop ignoring me on discord

**Comment by Artuto** [comment]
You clearly did not read the help command considering its right there

![](https://cdn.discordapp.com/attachments/319594058358194176/581865045693038613/Capture_2019-05-25-10-23-52.png)

**Comment by sastofficial** [comment]
i saw it now

**Comment by larsenv** [comment]
You could've also used https://bot.rc24.xyz/ and the link is on our site 😂
