### ISSUE TITLE
Birthdate Format

### ISSUE THREAD

**Issue by larsenv** [fl0co/RC24-Bot#87]
The birthday command should indicate that the format of the birthday is DD/MM. Why is it in that format anyway? I forgot why.

**Comment by Artuto** [comment]
> Why is it in that format anyway? I forgot why.

Because that's how normal people write the date.

**Comment by KcrPL** [comment]
Exactly lmao.

Day / Month / Year

**Comment by larsenv** [comment]
I wish we used DD/MM for dates here.

[Date formats are kind of a mess around the world.](https://en.wikipedia.org/wiki/Date_format_by_country)

**Comment by KcrPL** [comment]
Aren't we using Day/Month?

**Comment by Artuto** [comment]
![image](https://user-images.githubusercontent.com/9273973/63732991-4f90e680-c83c-11e9-8ad1-80b9fab2dc87.png)
Winning as always
